import { Button } from '@/components/ui/button';
import { Loading } from '@/components/ui/loading';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';

export default function Home() {
  const [loading, setLoading] = useState(true);

  const router = useRouter();

  const handleChatRedirect = () => {
    setLoading(true);

    setTimeout(() => {
      router.push('/chat');
    }, 1000);
  };

  return (
    <>
      <Head>
        <title>i7e | Everything AI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen bg-black">
        <div className="place-content-center h-screen w-screen grid">
          <Button
            onClick={handleChatRedirect}
            className="bg-white text-black hover:bg-white duration-150 flex items-center gap-3 transition-all border-none"
          >
            {loading ? <Loading /> : null}
            <p>Take me to I7E</p>
          </Button>
        </div>
      </main>
    </>
  );
}
